channels:
  - conda-forge
dependencies:
  - pandas==1.2.4
  - numpy==1.20.3
  - scikit-image
  - matplotlib==3.3.4
  - numba==0.53.1
  - pip
  - pip:
    - opencv_python-3.1.0-cp35-none-win_amd64.whl
